Empleando los datos del archivo './src/crypto_currency'.

- Cargue los datos en una base de datos apropiada.
- Lea mediante pandas las bases cargadas
- Emplee un metodo de concatenación para unificar la información.(debe considerar que se añadirá una columna adicional que especifique el tipo de moneda)
- Genere un agrupamiento de información a manera de obtener un resumen de los datos.
- Almacene dichos datos en un reporte excel.
- Apoyandose del ejercicio 2. Cree una imagen que sea guarda en el archivo excel
- Emplee un método de envio de correos

In [1]:
!pip install openpyxl

import sqlite3
import pandas as pd

# Leemos el dataset
df_crypto = pd.read_excel("./src/cripto_currency.xlsx")
df_crypto.head()

Requirement already satisfied: openpyxl in /usr/local/python/3.10.8/lib/python3.10/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /usr/local/python/3.10.8/lib/python3.10/site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 23.3 -> 23.3.1
[notice] To update, run: python -m pip install --upgrade pip

,Date,Open,High,Low,Close,Adj Close,Volume
0,2022-10-19,19335.027344,19348.416016,19127.687500,19139.535156,19139.535156,22425387184
1,2022-10-20,19138.085938,19315.199219,18971.458984,19053.740234,19053.740234,24493974420
2,2022-10-21,19053.203125,19237.384766,18770.970703,19172.468750,19172.468750,32459287866
3,2022-10-22,19172.380859,19248.068359,19132.244141,19208.189453,19208.189453,16104440957
4,2022-10-23,19207.734375,19646.652344,19124.197266,19567.007813,19567.007813,22128794335

In [2]:
#CARGAMOS LOS DATOS EN UNA BASE DE DATOS APROPIADA
conn = sqlite3.connect('crypto_data.db')
df_crypto.to_sql('crypto_data', conn, if_exists='replace')
conn.close()

In [6]:
#LEEMOS MEDIANTE PANDAS LA BASE CARGADA
conn = sqlite3.connect('crypto_data.db')
query = "SELECT * FROM crypto_data"
df_crypto = pd.read_sql(query, conn)
df_crypto.head()

,index,Date,Open,High,Low,Close,Adj Close,Volume
0,0,2022-10-19T00:00:00,19335.027344,19348.416016,19127.687500,19139.535156,19139.535156,22425387184
1,1,2022-10-20T00:00:00,19138.085938,19315.199219,18971.458984,19053.740234,19053.740234,24493974420
2,2,2022-10-21T00:00:00,19053.203125,19237.384766,18770.970703,19172.468750,19172.468750,32459287866
3,3,2022-10-22T00:00:00,19172.380859,19248.068359,19132.244141,19208.189453,19208.189453,16104440957
4,4,2022-10-23T00:00:00,19207.734375,19646.652344,19124.197266,19567.007813,19567.007813,22128794335

In [12]:
#EMPLEAMOS UN METODO DE CONCATENACION PARA UNIFICAR LA INFORMACION
query_add_column = "ALTER TABLE crypto_data ADD COLUMN 'Tipo de Moneda' TEXT"
conn.execute(query_add_column)

OperationalError: duplicate column name: Tipo de Moneda

In [13]:
query_update_column = "UPDATE crypto_data SET 'Tipo de Moneda' = 'Criptomoneda'"
conn.execute(query_update_column)

In [15]:
query_select_data = "SELECT * FROM crypto_data"
df_crypto = pd.read_sql(query_select_data, conn)
df_crypto.head()

,index,Date,Open,High,Low,Close,Adj Close,Volume,Tipo de Moneda
0,0,2022-10-19T00:00:00,19335.027344,19348.416016,19127.687500,19139.535156,19139.535156,22425387184,Criptomoneda
1,1,2022-10-20T00:00:00,19138.085938,19315.199219,18971.458984,19053.740234,19053.740234,24493974420,Criptomoneda
2,2,2022-10-21T00:00:00,19053.203125,19237.384766,18770.970703,19172.468750,19172.468750,32459287866,Criptomoneda
3,3,2022-10-22T00:00:00,19172.380859,19248.068359,19132.244141,19208.189453,19208.189453,16104440957,Criptomoneda
4,4,2022-10-23T00:00:00,19207.734375,19646.652344,19124.197266,19567.007813,19567.007813,22128794335,Criptomoneda

In [ ]:
#GENERAMOS UN AGRUPAMIENTO DE INFORMACION A MANERA DE OBTENER UN RESUMEN DE LOS DATOS